### ISSUE TITLE
A really annoying bug with auto-formatting

### ISSUE THREAD

**Issue by SpejCZ** [TheRealSyler/vscode-sass-indented#23] opened 2019-10-01 19:32 UTC
**Describe the bug**
It's a bug with autoformatter
It moves the things in the media query to the starting point of the media query, which is really annoying because it breaks the entire code.

**To Reproduce**
Write the following into a sass file, format it and compile, it returns broken css:
```
.foo
  position: relative

  @media only screen and (min-width: 600px)
    .foo
    position: absolute

  & > .bar
    width: 100%
```

**Expected behavior**
I expected it to format the .bar in the media query,

**Screenshots**
If you add screen shots of code, please also paste the code as text so that i can just copy the code and reproduce the bug.

My code before formatting:
![image](https://user-images.githubusercontent.com/30202541/65994060-c7cd7600-e492-11e9-93ef-bcf4daf48d27.png)

After i format it:
![image](https://user-images.githubusercontent.com/30202541/65994070-cdc35700-e492-11e9-847b-e321707394e9.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version (of the extension) newest

**Additional context**

> Sorry if it doesn't make sense, It is just really hard to describe

**Comment by TheRealSyler** [comment] 2019-10-01 22:14
this is technically expected behavior, but i see why this might bother you, the reason why this happens is the formatter goes trough the file from top to bottom and there is a rule that selectors can only be indented one tab size from the last selector so in this example the second `.item` cant be indented to further, as far as the formatter is concerned the media query doesn't exist, so there are three possible solutions.

first solution
```sass
.foo
  position: relative
  @media only screen and (min-width: 600px)
    ///R use the R option this resets the indentation of the selectors.
    .foo
      position: absolute
```
Second solution, move the media query.
```sass
.foo
  position: relative
@media only screen and (min-width: 600px)
  .foo
    position: absolute
```
third solution edit the formatter yourself and add the rule that media queries count as selectors, or wait until i do it (this will take a while if it happens at all), if you  want to change the behavior you need to fork and change this [repo](https://github.com/TheRealSyler/sass-formatter), it should be relatively easy to change.

**Comment by TheRealSyler** [comment] 2019-10-03 17:44
i fixed it,  i will wait updating the extension until i made more changes since this is just a minor bug.

**Comment by SpejCZ** [comment] 2019-10-03 18:20
Okay, thank you for help


Od: TheRealSyler
Odesláno:čtvrtek 3. října 2019 19:44
Komu: TheRealSyler/vscode-sass-indented
Kopie: SpejCZ; Author
Předmět: Re: [TheRealSyler/vscode-sass-indented] A really annoying bug withauto-formatting (#23)

i fixed it, i will wait updating the extension until i made more changes since this is just a minor bug.

**Comment by PinkiePieStyle** [comment] 2019-10-08 12:14
Same Problem
Left is before and Right after Format
other is from comment here 

> Second solution, move the media query.

but formats wrong and gives wrong css too
![sassformat](https://user-images.githubusercontent.com/7350146/66393513-07d0b380-e9d3-11e9-93cf-92bfcaa8376b.png)

Correct output gives only Code below when using format (using //R is crap its easier not using format)
```
.class
    .class
        color: none

        span
            color: none

            @for $i from 0 through 2
                //R
                &:nth-child(#{$i})
                    color: none

    > span
        //R
        color: none
```

```
.class .class {
  color: none; }
  .class .class span {
    color: none; }
    .class .class span:nth-child(0) {
      color: none; }
    .class .class span:nth-child(1) {
      color: none; }
    .class .class span:nth-child(2) {
      color: none; }

.class > span {
  color: none; }
```

But lines like this doesnt format
```
.class
    background-image: linear-gradient(to bottom,                #fff 0%,                #000             100%   )
```

**Comment by TheRealSyler** [comment] 2019-10-08 12:41
@PinkiePieStyle i thought that the `@for` and `@each` stuff already works, but i guess ill have to fix that too, the //R is meant to be used as a work around until the formatter works as expected, the `>` thing will also be fixed  in the next version, and the reason why the last example doesn't format is because its just not implemented yet, feel free to add stuff you feel is missing yourself (specifically the last example not the other ones).

**Comment by TheRealSyler** [comment] 2019-10-08 15:02
all of the issues should be addressed by the latest release, except this `background-image: linear-gradient(to bottom,                #fff 0%,                #000             100%   )` is still expected behavior,

**Closed by TheRealSyler** 2019-10-08 15:02 UTC
Labels: bug
